---
- name: AltSchool Africa Holiday Challenge
  hosts: Servers
  become: true
  tasks:
          - name: install updates on ubuntu server
            tags: update
            apt:
                    upgrade: dist
                    force_apt_get: yes
                    update_cache: yes

          - name: Install ufw
            tags: ufw
            apt:
                    name: ufw
                    state: present

          - name: Allow HTTPS access
            tags: ufw
            ufw:
                    rule: allow
                    port: 443
                    proto: tcp

          - name: Allow HTTP accesss
            tags: ufw
            ufw:
                    rule: allow
                    port: 80
                    proto: tcp

          - name: Allow SSH access
            tags: ufw
            ufw:
                    rule: allow
                    port: 22
                    proto: tcp

          - name: Enable ufw
            ufw:
                    state: enabled
                    direction: in

          - name: Install NGINX
            apt:
                    name: nginx
                    state: present

          - name: Start NGINX service
            service:
                    name: nginx
                    state: started
                    enabled: yes
          
          - name: Create home page
            copy:
                    src: files/index.html
                    dest: /var/www/index.html
                    owner: www-data
                    group: www-data
                    mode: 0644

