---
- name: AltSchool Africa Holiday Challenge
  hosts: Servers
  become: true
  tasks:
          - name: install updates on ubuntu server
            tags: update
            apt:
                    upgrade: dist
                    force_apt_get: yes
                    update_cache: yes

          - name: Install ufw
            tags: ufw
            apt:
                    name: ufw
                    state: present

          - name: Allow HTTPS access
            tags: ufw
            ufw:
                    rule: allow
                    port: 443
                    proto: tcp

          - name: Allow HTTP accesss
            tags: ufw
            ufw:
                    rule: allow
                    port: 80
                    proto: tcp

          - name: Allow SSH access
            tags: ufw
            ufw:
                    rule: allow
                    port: 22
                    proto: tcp

          - name: Enable ufw
            tags: ufw
            ufw:
                    state: enabled
                    direction: in

          - name: Install NGINX
            tags: nginx
            apt:
                    name: nginx
                    state: present

          - name: Edit NGINX config file for default homepage
            tags: nginx
            blockinfile:
                    path: /etc/nginx/sites-enabled/default
                    block: |
                            server {
                                    listen 85 default_server;
                                    listen [::]:85 default_server;

                                    root /var/www/html;
                                    index index.html index.htm;

                                    server_name _;

                                    location / {
                                            try_files $uri $uri/ =404;
                                    }
                            }

          - name: Start NGINX service
            tags: nginx
            service:
                    name: nginx
                    state: started
                    enabled: yes

          - name: Get host info
            shell: hostnamectl | grep "Static"
            register: host_info
         
          - name: Render home page
            template:
                    src: files/index.html.j2
                    dest: /var/www/html/index.html
                    owner: www-data
                    group: www-data
                    mode: 0644

          - name: Block access through public IP
            lineinfile:
                    path: /etc/nginx/sites-available/default
                    regexp: '^(\s*deny\s+).*'
                    line: '\1$remote_addr;'
                    backrefs: yes
                    state: present
            notify:
                    - restart nginx

          - name: allow access through ALB
            lineinfile:
                    path: /etc/nginx/sites-available/default
                    regexp: '(\s*allow\s+).*'
                    line: '\1$http_x_forwarded_for;'
                    backrefs: yes
                    state: present
            notify:
                    - restart nginx

          - name: remove default server block
            lineinfile:
                    path: /etc/nginx/nginx.conf
                    regexp: '^(\s*include\s+/etc/nginx/sites-enabled/\*;)'
                    state: absent
            notify:
                    - restart nginx


  handlers:
          - name: restart nginx
            service:
                    name: nginx
                    state: restarted
