---
- name: AltSchool Africa Terraform Mini Project
  hosts: servers
  become: true
  tasks:
          - name: install updates on ubuntu server
            tags: update
            apt:
                    upgrade: dist
                    force_apt_get: yes
                    update_cache: yes

          - name: install apache for ubuntu server
            tags: apache
            apt:
                    name:
                            - apache2
                    state: present

          - name: Start Apache web server
            service:
                    name: apache2
                    state: started

          - name: set system timezone
            copy:
                content: "Africa/Lagos\n"
                dest: /etc/timezone
                owner: root
                group: root
                mode: 0644
            register: timezone

          - name: reconfigure the system after setting timezone
            shell: dpkg-reconfigure --frontend noninteractive tzdata
            when: timezone.changed

          - name: Get host info
            shell: hostnamectl | grep "Static"
            register: host_info

          - name: Render custom home page
            template:
                    src: files/index.html.j2
                    dest: /var/www/html/index.html
                    owner: www-data
                    group: www-data
                    mode: 0644

          - name: Restart Apache
            become: yes
            service:
                   name: apache2
                   state: restarted

