---
- name: AltSchool Africa Terraform Mini Project
  hosts: Servers
  become: true
  tasks:
          - name: install updates on ubuntu server
            tags: update
            apt:
                    upgrade: dist
                    force_apt_get: yes
                    update_cache: yes

          - name: install apache for ubuntu server
            tags: apache
            apt:
                    name:
                            - apache2
                    state: latest
