---
- name: AltSchool Africa Terraform Mini Project
  hosts: Servers
  become: true
  tasks:
          - name: install updates on ubuntu server
            tags: update
            apt:
                    upgrade: dist
                    force_apt_get: yes
                    update_cache: yes

          - name: install apache for ubuntu server
            tags: apache
            apt:
                    name:
                            - apache2
                    state: latest

          - name: set system timezone
            copy:
                content: "Africa/Lagos\n"
                dest: /etc/timezone
                owner: root
                group: root
                mode: 0644
            register: timezone

           - name: reconfigure the system after setting timezone
             shell: dpkg-reconfigure --frontend noninteractive tzdata
             when: timezone.changed
