---

- hosts: all
  become: true
  tasks:
    - name: install apache and php packages
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: set system timezone
      copy:
          content: "Africa/Lagos\n"
          dest: /etc/timezone
          owner: root
          group: root
          mode: 0644
      register: timezone

    - name: reconfigure the system after setting timezone
      shell: dpkg-reconfigure --frontend noninteractive tzdata
      when: timezone.changed

    - name: copy default page for server
      copy:
          src: default_page.php
          dest: /var/www/html/index.php
          owner: root
          group: root
          mode: 0644
    
    - name: restart apache2 service
      service:
        name: apache2
        state: restarted