---

- hosts: all
  become: true
  pre_tasks:
          - name: Install PostgreSQL packages
            tags: database,postgresql
            apt:
                    name:
                            - postgresql
                            - postgresql-contrib
                    state: present
          
          - name: Install Python package for postgres
            tags: python,database
            pip:
                    name:
                            - psycopg2-binary

  tasks:
          - name: Find out if PostgreSQL is initialized
            ansible.builtin.stat:
                    path: "/var/lib/pgsql/data/pg_hba.conf"
                    register: postgres_data

          - name: Initialize PostgreSQL
            shell: "postgresql-setup initdb"
            when: not postgres_data.stat.exists

          - name: Start and enable postgres service
            service:
                    name: postgresql
                    state: started
                    enabled: yes
