---

- hosts: all
  become: true
  pre_tasks:
          - name: Install PostgreSQL packages
            tags: database,postgresql
            apt:
                    name:
                            - postgresql
                            - postgresql-contrib
                    state: present

          - name: Install Pip3
            apt:
                    name:
                            - python3-pip
          
          - name: Install Python package for postgres
            tags: python,database
            ansible.builtin.pip:
                    name:
                            - psycopg2-binary

  tasks:
          - name: Start and enable postgres service
            service:
                    name: postgresql
                    state: started
                    enabled: yes
