---

- hosts: all
  become: true
  pre_tasks:
          - name: Install PostgreSQL packages
            tags: database,postgresql
            apt:
                    name:
                            - postgresql
                            - postgresql-contrib
                    state: present

          - name: Install Pip3
            apt:
                    name:
                            - python3-pip
          
          - name: Install Python package for postgres
            tags: python,database
            ansible.builtin.pip:
                    name:
                            - psycopg2-binary

  tasks:
          - name: Find out if PostgreSQL is initialized
            ansible.builtin.stat:
                    path: "/etc/postgresql/14/main/pg_hba.conf"
            register: postgres_data

          - name: Initialize PostgreSQL
            shell: "postgresql-setup initdb"
            when: not postgres_data.stat.exists

          - name: Start and enable postgres service
            service:
                    name: postgresql
                    state: started
                    enabled: yes

          - name: Allow md5 connect for the db user
            postgresql_pg_hba:
                    dest: "/etc/postgresql/14/main/pg_hba.conf"
                    contype: host
                    databases: all
                    method: md5
                    users: postgres
                    create: true
                    # become: true
                    #become_user: postgres
            notify: restart postgres

                    #- name: Create app database
                    #postgresql_db:
                    #state: present
                    #name: "exam-project-db"
                    #become: yes
                    #become_user: postgres
  
  handlers:
          - name: restart postgres
            service:
                    name: postgresql
                    state: restarted

