---

- hosts: all
  become: true
  tasks:
          - name: install updates on ubuntu server
            tags: update
            apt:
                    upgrade: dist
                    force_apt_get: yes
                    update_cache: yes

          - name: install apache and php packages for ubuntu server
            tags: ubuntu,apache,php
            apt:
                    name:
                            - apache2
                            - libapache2-mod-php
                    state: latest

          - name: enable ufw
            tags: ufw,service
            community.general.ufw:
                    state: enabled

          - name: start ufw service
            service:
                    name: ufw
                    state: started

          - name: Allow Apache Full
            community.general.ufw:
                    rule: allow
                    name: Apache Full
          - name: Allow OpenSSH
            community.general.ufw:
                    rule: allow
                    name: OpenSSH


