---

- hosts: all
  become: true
  tasks:
          - name: install updates on ubuntu server
            tags: update
            apt:
                    upgrade: dist
                    force_apt_get: yes
                    update_cache: yes
